// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwWWxTy8HVFJxGqruSf89KKGNE1HGmXWU',
    appId: '1:718657603869:web:43279af001ad071a3279f4',
    messagingSenderId: '718657603869',
    projectId: 'food-go-1f662',
    authDomain: 'food-go-1f662.firebaseapp.com',
    storageBucket: 'food-go-1f662.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlYRKndLIKuE2WIp2jdBsdhVccqJIVqJo',
    appId: '1:718657603869:android:2d28f43e9f3f509d3279f4',
    messagingSenderId: '718657603869',
    projectId: 'food-go-1f662',
    storageBucket: 'food-go-1f662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtcKNMZn8kyt7xd51YJzZOZ95ajc7-LgQ',
    appId: '1:718657603869:ios:81028e2fada23dd33279f4',
    messagingSenderId: '718657603869',
    projectId: 'food-go-1f662',
    storageBucket: 'food-go-1f662.appspot.com',
    iosBundleId: 'com.example.foodGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwWWxTy8HVFJxGqruSf89KKGNE1HGmXWU',
    appId: '1:718657603869:web:d11183b20f5b86963279f4',
    messagingSenderId: '718657603869',
    projectId: 'food-go-1f662',
    authDomain: 'food-go-1f662.firebaseapp.com',
    storageBucket: 'food-go-1f662.appspot.com',
  );
}
